export const dataFile = {
    validEmail: 'AkramTest@gmail.com',
    validPassword: 'test123',
    validName: 'Akram',
    invalidEmail: 'invalid@test.com',
    invalidPassword: 'invalid123',
    password: 'test123',
    firstName: 'Test',
    lastName: 'User',
    company: 'Test Company',
    address1: '123 Test Street',
    address2: 'Apt 1',
    city: 'Test City',
    state: 'Test State',
    zipCode: '12345',
    mobileNumber: '1234567890',
    validSubject: 'Test Subject',
    validMessage: 'Test Message',
    cardName: 'Test User',
    cardNumber: '4100000000000',
    cvc: '123',
    expiryMonth: '01',
    expiryYear: '2026',
};